services:
  todo_backend_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  todo_backend_app:
    image: backend_todo
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - todo_backend_database
    env_file:
      - .env

volumes:
  pgdata: